EXPERIMENT:
  NAME: ""
  TAG: "dkd,res34,res18"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 16 #32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "DKD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.025 #0.2*(128/512)
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
DKD:
  CE_WEIGHT: 1.0
  BETA: 0.5 #1.5
  T: 1.0 #1.25
  WARMUP: 1