EXPERIMENT:
  NAME: ""
  TAG: "sdd_kd,res34,res18"
  PROJECT: "imagenet_baselines_5"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 16
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "SDD_KD"
  TEACHER: "ResNet34_sdd"
  STUDENT: "ResNet18_sdd"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
KD:
  TEMPERATURE: 1.0
  LOSS:
    CE_WEIGHT: 1.0
    KD_WEIGHT: 0.5
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 200