EXPERIMENT:
  NAME: ""
  TAG: "sdd_rld,wrn_40_2,wrn_16_2"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SDD_RLD"
  TEACHER: "wrn_40_2_sdd"
  STUDENT: "wrn_16_2_sdd"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
