EXPERIMENT:
  NAME: ""
  TAG: "sdd_dkd,res50,mv2"
  PROJECT: "imagenet_baselines_5"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 16
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "SDD_DKD"
  TEACHER: "ResNet50_sdd"
  STUDENT: "MobileNetV2_sdd"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.025
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
DKD:
  CE_WEIGHT: 1.0
  BETA: 0.5
  T: 1.0
  WARMUP: 1